### ISSUE TITLE
RenderingFreeTypeOpenGL was dropped from VTK 6.3

### ISSUE THREAD

**Issue by rdmitry** [thliebig/QCSXCAD#2]
QCSXCAD uses RenderingFreeTypeOpenGL, but

>Note that the deprecated RenderingFreeTypeOpenGL module has been removed, as the functionality of this module has been replaced by the vtkTextRenderer and vtkTextMapper classes.

See http://www.kitware.com/blog/home/post/963

**Comment by thliebig** [comment]
Thanks for the info. I'm just not yet sure what this means. Do I have to change some code or just which libraries QCSXCAD links? I will have a closer look.

**Comment by rdmitry** [comment]
Unfortunately I can't provide any details now. I'm not specialist in VTK, just working on rpm packages for openSUSE.

**Comment by rdmitry** [comment]
You don't use RenderingFreeTypeOpenGL in the code. Looks like this line was from http://www.vtk.org/Wiki/VTK/VTK_6_Migration/Factories_now_require_defines, so we can simply remove vtkRenderingFreeTypeOpenGL.

**Comment by thliebig** [comment]
Thanks for the patch, I totally forgot about this issue. Do you use Qt5 and vtk6 on Linux? I still have issues with this combination. Somehow qt5 does not properly handle the vtk events.

**Comment by rdmitry** [comment]
Yes, I'm using Qt5 and VTK-6.3 on openSUSE. But looks like we have problems with VTK build config, so I need to fix it first.

**Comment by thliebig** [comment]
Let me know if you get it working. I was able to build using qt5 and vtk6.x in the past. But trying to move or rotate something in AppCSXCAD was laggy due to some bug in qt5 handling x11 events (see http://markmail.org/message/l76z3mppijvpy6sn). It is supposed to be fixed in qt5.6 but I have not tried it.

**Comment by thliebig** [comment]
I have made some changes to the build system and build successfully on openSUSE. Please test the latest version.

**Comment by rdmitry** [comment]
Thanks, looks like build problems are solved.
